#!/usr/bin/env python3
"""
Passenger — tournament-mode image comparison tool.

Serves passenger.html and the images in a given output directory so you can
pick winners in head-to-head matchups until one image per subject remains.

Usage:
  python3 passenger.py /path/to/output-dir
  python3 passenger.py   # defaults to current directory

The directory must contain:
  manifest.json   — generated by any batch script (run-tuning-batch, run-quality-comparison, etc.)
  *.png           — the generated images
  *.json          — per-image sidecar files (for hover metadata)
"""
import http.server
import os
import shutil
import sys
from pathlib import Path

PORT = 8189

directory = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()

if not directory.is_dir():
    print(f"ERROR: not a directory: {directory}", file=sys.stderr)
    sys.exit(1)

if not (directory / "manifest.json").exists():
    print(f"ERROR: no manifest.json in {directory}", file=sys.stderr)
    print("Run a batch script first to generate output.", file=sys.stderr)
    sys.exit(1)

# Copy passenger.html from repo root into the output dir if needed
script_dir = Path(__file__).parent
src_html   = script_dir / "passenger.html"
dst_html   = directory  / "passenger.html"
if src_html.exists() and not dst_html.exists():
    shutil.copy2(src_html, dst_html)
elif not dst_html.exists():
    print("WARNING: passenger.html not found — UI may not load", file=sys.stderr)

os.chdir(directory)


class Handler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Cache-Control", "no-cache")
        super().end_headers()

    def do_GET(self):
        if self.path == "/":
            self.path = "/passenger.html"
        return super().do_GET()

    def log_message(self, *_):
        pass  # suppress per-request noise


server = http.server.HTTPServer(("0.0.0.0", PORT), Handler)
print(f"Passenger → http://localhost:{PORT}")
print(f"Directory: {directory}")
print("Press Ctrl+C to stop.")
try:
    server.serve_forever()
except KeyboardInterrupt:
    print("\nStopped.")
